### ISSUE TITLE
Are you still maintaining this?

### ISSUE THREAD

**Issue by excid3** [matiasgagliano/action_access#1]
I love the syntax of this gem. It brings a lot of clarity that was missing in other authorization gems. Great work on it so far!

Are you still maintaining this gem? Do you have plans for it moving forward?

**Comment by matiasgagliano** [comment]
Yes, I have full intention to keep maintaining it.

There are no new commits because, as you can see, no issues have been reported (this is #1) and I haven't faced any case that really requires extra features. The gem is (as always has been) up for expansion, reasonable new features and pull requests.

Thanks for the complements, I'm glad that people can enjoy it.
