### ISSUE TITLE
Require specific parameters and values (optionally database dependent) for specific actions.

### ISSUE THREAD

**Issue by god-anubis** [matiasgagliano/action_access#6]
One functionality I miss is to make certain actions only available to users if they supply a specific set of parameters.

A classic example would be the user who may only edit their own profile but not somebody else's. Do you have any thought on how to best implement such functionality in action_access?

**Comment by matiasgagliano** [comment]
[Here](https://github.com/matiasgagliano/action_access#fine-grained-access-control) you'll find just what you need.

**Comment by god-anubis** [comment]
You are of course right. The only reason that got me to think about implementing something is that by using not_authorized! the action has to be attempted in order to know if it will pass or if it is not authorized. However I would like to know this without calling the action, so I could decide if a link to an action should be displayed in the first place or not. Obviously one could put the same logic of not_authorized! from the action into the view/controller/wherever that decides if the link should be displayed but ideally I would prefer a more DRY solution.

**Comment by matiasgagliano** [comment]
There's a similar question in #2.

This case breaks into two matters, how to filter access in controllers and how to check if access is allowed from views.

For the first part, authorization is based only on *clearance level* and *action*. If you have more specific restrictions you have to allow access to the action, check the specifics within the action and call `not_authorized!` before continuing when not allowed.

```ruby
class ArticlesController < ApplicationController
  let :authors, [:edit, :destroy]

  def edit
     not_authorized! unless @article.in? current_user.articles
     # ...
  end

   # ...
end
```

Access to the action is not a problem because the rest won't get executed if not allowed. This makes restrictions much clearer and easier to debug than having the logic for every case bundled in `current_clearance_level`.

You could also use hooks to clean it up:

```ruby
class ArticlesController < ApplicationController
  let :authors, [:edit, :destroy]
  before_action :check_author, only: [:edit, :destroy]

  def edit
     # ...
  end

  private

    def check_author
      not_authorized! unless @article.in? current_user.articles
    end
end
```

For the second matter, you should use the **helpers provided** to check what's allowed and display links accordingly. The easiest way is using `can?` from [Model Additions](https://github.com/matiasgagliano/action_access#model-additions):

```erb
<% if current_user.can? :edit, :articles %>
  <%= link_to 'Edit article', edit_article_path(@article) %>
<% end %>
```

If you don't have a `User` model you can use the `keeper `:

```erb
<% if keeper.lets? current_role, :edit, :articles %>
  <%= link_to 'Edit article', edit_article_path(@article) %>
<% end %>
```

Hope this clarifies the whole stack for allowing and checking permissions.
